// This enum was generated by Dialoguer
public enum DialoguerDialogues{
	Intro = 0,
	ShammyIntro = 1,
	AlexiaIntro = 2,
	NoelCase = 3,
	CarlosCase = 4,
	AlexiaendCase = 5,
	PilotIntro = 6,
	AlexiaandMay = 7,
	Bed = 8,
}
