// This enum was generated by Dialoguer
public enum DialoguerDialogues{
	Intro = 0,
	ShammyIntro = 1,
	AlexiaIntro = 2,
	NoelCase = 3,
	CarlosCase = 4,
	AlexiaendCase = 5,
	PilotIntro = 6,
	AlexiaandMay = 7,
<<<<<<< HEAD
	Bed = 8,
=======
>>>>>>> 4ec89bd0f4d4f44c3a2cb564d6d57288e05626bf
}
